### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by pantharshit00** [blakeathomas/blog#2]
you should have included the build in this repo not the source .
Make another repo for source.

See like I have done for my portfolio.
https://github.com/pantharshit00?tab=repositories

**Comment by blakeathomas** [comment]
What do u mean?

**Comment by pantharshit00** [comment]
you should make a separate repo to store the build. then go to settings tab of the repo and enable gtihub pages

Steps:
1. make a empty repo named blog. (rename this to blog-src)
2. build your current blog by yarn build
3. Copy the build to the empty repo and push it to github
4. enable github pages from settings of your repo
5. Your are now good to go!

checkout https://now.sh for even simpler deployment
